# Change these first
owner: biginvn # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Agoyu
    url: https://agoyu.com/
    tag: AGOYU
  - name: GO Portal
    url: https://goportal-uat.bigin.top/
    tag: GOPORTAL
  - name: International booking
    method: POST
    url: https://agoyu.com/api/booking/estimation
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Fake API testing
    method: POST
    url: https://agoyu.com/api/fake-api/post
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: International booking - Quotation
    method: POST
    url: https://agoyu.com/api/booking/market-place/123
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Domestic booking
    method: POST
    url: https://agoyu.com/api/booking/estimation
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Domestic booking - Quotation
    method: POST
    url: https://agoyu.com/api/booking/market-place/123
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Change Status Booking
    method: POST
    url: https://agoyu.com/api/consumer/moving-plan/cancel/12
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Register new account
    method: POST
    url: https://agoyu.com/api/consumer/auth/register
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Consumer Send message
    method: POST
    url: https://agoyu.com/api/notification/chat/new-message
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Manage Account - Agoyu User
    method: GET
    url: https://agoyu.com/ajax/agoyu/agoyu-user/get-agoyu-user
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Manage Account - Consumer
    method: GET
    url: https://agoyu.com/ajax/agoyu/consumer/consumers
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Manage Account - Mover
    method: GET
    url: https://agoyu.com/ajax/agoyu/mover/agoyu-get-movers
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: International Moving Rate
    method: GET
    url: https://agoyu.com/ajax/agoyu/mover/international-rates/manage-rates/custom-rate/list
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Domestic Moving Rate
    method: GET
    url: https://agoyu.com/ajax/agoyu/mover/domestic-rates/vehicle-rates/list
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Manage weight Mapping
    method: GET
    url: https://agoyu.com/ajax/agoyu/manage-weight-mapping/search
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Market Place
    method: GET
    url: https://agoyu.com/api/consumer/quotations
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Manage Page
    method: GET
    url: https://agoyu.com/ajax/pages/template-content/homepage?pageSlug=homepage
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Market Place
    method: GET
    url: https://agoyu.com/api/mover/quotations
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Ping-back Moving Rate
    method: GET
    url: https://agoyu.com/api/mover/pingback/406
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Open API
    method: GET
    url: https://agoyu.com/api/mover/webhook?page=1&limit=10
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: International Moving Rate
    method: GET
    url: https://agoyu.com/ajax/agoyu/mover/international-rates/manage-rates/custom-rate/list
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Domestic Moving Rate
    method: GET
    url: https://agoyu.com/ajax/agoyu/mover/domestic-rates/vehicle-rates/list
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Manage User
    method: GET
    url: https://agoyu.com/ajax/mover/movers
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Manage Booking Request
    method: GET
    url: https://agoyu.com/api/mover/booking
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Register new account
    method: POST
    url: https://agoyu.com/api/mover/auth/register
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Mover Send message
    method: POST
    url: https://agoyu.com/api/mover/chat/send-notification
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Logout
    method: POST
    url: https://agoyu.com/api/custom-user/auth/logout
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Login
    method: POST
    url: https://agoyu.com/api/custom-user/auth/login
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Google API
    method: GET
    url: https://agoyu.com/api/google/detail-place?address=123
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Upload media
    method: POST
    url: https://agoyu.com/api/media/uploadSingle
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Consumer list moving plan
    method: GET
    url: https://agoyu.com/api/consumer/moving-plan
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Consumer detail moving plan
    method: GET
    url: https://agoyu.com/api/consumer/moving-plan/12
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Consumer detail moving plan audit log
    method: GET
    url: https://agoyu.com/api/consumer/moving-plan/audit-log/12
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Consumer list notification
    method: GET
    url: https://agoyu.com/api/consumer/notifications?page=1&limit=10
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Get data SEO page
    method: POST
    url: https://agoyu.com/api/page/homepage
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Consumer profile
    method: GET
    url: https://agoyu.com/api/consumer/profile
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Consumer quotation detail
    method: GET
    url: https://agoyu.com/api/consumer/quotations/12
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: Reference booking
    method: GET
    url: https://agoyu.com/api/references
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
  - name: List room temp booking
    method: POST
    url: https://agoyu.com/api/consumer/survey/room-temp?booking_id=12
    tag: AGOYU
    headers:
      - "Content-Type: application/json"
      - "Accept: application/json"
    expectedStatusCodes:
      - 200
      - 422
      - 401
      - 400
status-website:
  theme: light
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  baseUrl: /upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
