# Change these first
owner: biginvn # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: Agoyu
    url: https://agoyu.com/
  - name: Login
    method: POST
    url: https://agoyu.com/api/custom-user/auth/login
    headers:
      - "Content-Type: application/json"
    expectedStatusCodes:
      - 200
      - 422
  - name: Agoyu QA
    url: https://agoyu-qa.bigin.top/
  - name: Agoyu UAT
    url: https://agoyu-uat.bigin.top/
  - name: Agoyu STAGING
    url: https://preview.agoyu.com/
status-website:
  theme: light
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  baseUrl: /upptime
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
